client/.gitignore
client/index.html
client/package-lock.json
client/package.json
client/rollup.config.js
client/src/App.jsx
client/src/index.js

Initial set up front-end part of application.
To run client:
* Go to client folder
* npm i
* npm run build
* open client/index.html file in bowser
Notes:
* https://rollupjs.org is used as module bundler
* node v16.13.0
* npm 8.1.0

ui hello world

---

client/index.html
client/src/App.jsx
client/src/pages/Login/FormField.jsx
client/src/pages/Login/Login.jsx
client/src/pages/Login/index.js
client/src/style.css
client/src/utils.js

introduce login form

---

docker-deployment/doky-server/README.md
docker-deployment/doky-server/dev.yml
server/build.gradle

Create docker image and docker compose configuration so project can be built and run easily.

Create docker image

---

docker-deployment/doky-server/Dockerfile
docker-deployment/doky-server/README.md
docker-deployment/doky-server/dev.yml

- fix problem when server cannot to connect to db when started

Build Docker image

---

server/README.md
server/build.gradle
server/src/main/java/org/hkurh/doky/ApiDocumentationConfig.java
server/src/main/java/org/hkurh/doky/controllers/AuthorizationUserApi.java
server/src/main/java/org/hkurh/doky/controllers/AuthorizationUserController.java
server/src/main/java/org/hkurh/doky/controllers/DocumentApi.java
server/src/main/java/org/hkurh/doky/controllers/DocumentController.java
server/src/main/java/org/hkurh/doky/controllers/UserApi.java
server/src/main/java/org/hkurh/doky/controllers/UserController.java
server/src/main/java/org/hkurh/doky/security/AuthenticationRequest.java
server/src/main/resources/application.properties

33 open api swagger documetntation for endpoints

---

server/src/main/java/org/hkurh/doky/security/WebSecurityConfig.java

Configured to allow requests to all endpoints from all origins.
Not very secure :)

CORS Configuration

---

server/src/apiTest/resources/sql/DocumentSpec/setup.sql
server/src/main/java/org/hkurh/doky/ApiDocumentationConfig.kt
server/src/main/java/org/hkurh/doky/documents/DocumentDto.kt
server/src/main/java/org/hkurh/doky/documents/DocumentEntity.kt
server/src/main/java/org/hkurh/doky/security/DokyUserDetails.kt
server/src/main/java/org/hkurh/doky/security/SpringSecurityAuditorAware.kt
server/src/main/java/org/hkurh/doky/users/UserServiceImpl.kt
server/src/main/resources/db/migration/V9__audit_info_for_documents.sql

Add auditing to Document entity.
API and UI changes will be done in separate task

MAIN-T-47 add changes history for document

---

.space.kts

Tag cannot be added :(
So just done adjustment - run tests for any push in development branches

MAIN-T-74 Add git tag to deployed revision

---

.github/workflows/gradle.yml
.space.kts

MAIN-T-91 Github Action CI

---

.space.kts
server/build.gradle
server/src/main/java/org/hkurh/doky/DokyController.kt
server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/src/main/resources/application.properties

Set env variables with build number and commit hash during deployment
Get this info and return with new endpoint `/version`

MAIN-T-103 Create endpoint to get current BE build number

---

.space.kts

Change the trigger to run it once a day instead of for each push.

MAIN-T-104 Schedule run job for main once a day

---

.space.kts
README.md
server/build.gradle
server/src/main/java/org/hkurh/doky/DokyController.kt

Pass build number to gradl and use it in deployment

MAIN-T-107 No version is shown

---

server/src/apiTest/java/org/hkurh/doky/DocumentSpec.kt
server/src/apiTest/resources/sql/DocumentSpec/setup.sql
server/src/main/java/org/hkurh/doky/DokyMapper.kt
server/src/main/java/org/hkurh/doky/documents/api/DocumentController.kt

Populate filename from entity to dto.

MAIN-T-88 Adjust Document API to return information about attached document

---

.space.kts
server/build.gradle
server/qodana.yaml

Run all tests for coverage.
Use one run task for all tests to optimize run time.

MAIN-T-108 Add Integration and API tests to coverage

---

server/src/main/resources/application-dev.properties
server/src/main/resources/application-local.properties
server/src/main/resources/application.properties

MAIN-T-110 Reduce logs on DEV

---

server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/src/main/resources/application-local.properties
server/src/main/resources/application-test.properties
server/src/main/resources/application.properties
server/src/main/resources/bootstrap-local.properties
server/src/main/resources/bootstrap-test.properties
server/src/main/resources/bootstrap.properties

Update app properties and enable Azure app configuration
The update includes changes to server properties to disable attributes, such as file storage and mail password, for enhanced security. The Azure application configuration on local and bootstrap properties have been enabled for better application management and monitoring. File storage paths have been modified for test and local configurations.

DOKY-159 Move app configuration to Azure Configuration

---

server/doky-front/.husky/pre-commit
server/doky-front/package.json

https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory

DOKY-162 adjust husky pre-commit hooks

---

server/src/main/kotlin/org/hkurh/doky/DokyApi.kt
server/src/main/kotlin/org/hkurh/doky/DokyController.kt
server/src/main/kotlin/org/hkurh/doky/documents/api/DocumentApi.kt
server/src/main/kotlin/org/hkurh/doky/password/api/PasswordApi.kt

Add `DokyApi` interface and enhance API responses
Introduce the `DokyApi` interface for general app info and update `DokyController` to implement it. Also, refine response annotations in `PasswordApi` and `DocumentApi` to improve clarity and coverage.

DOKY-114 Improve swagger documentation

---

server/doky-front/src/api/users.js
server/doky-front/src/components/formComponents/FormInput.jsx
server/doky-front/src/hooks/useForm.js
server/doky-front/src/pages/Login/Login.jsx
server/doky-front/src/pages/ResetPassword/ResetPassword.jsx
server/doky-front/src/pages/ResetPassword/index.js
server/doky-front/src/pages/ResetPassword/useRequestResetPassword.js
server/doky-front/src/routing/routes.js

Add password reset functionality
Implemented password reset request page and necessary backend API calls. Updated the routing to include the new reset password page and adjusted the login page to link to it.

DOKY-174 Create Page to send Restore Password Request

---

email-service/src/main/kotlin/org/hkurh/doky/KafkaConsumerConfig.kt
email-service/src/main/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationConsumerService.kt
email-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
email-service/src/main/resources/application.properties

Configure Kafka poll interval and deserializer default type.
Add concurrency, auto-reset settings and acknowledgement mode settings to Kafka consumer.

DOKY-172 Create separate email service

---

app-server/build.gradle.kts
app-server/src/main/resources/application-test.properties
email-service/build.gradle.kts

Refactor build scripts and improve test configuration
Removed conditional checks for running tests, standardized version properties in dependencies, and corrected database URL in test properties. These changes aim to streamline the build process and ensure consistency across different environments.

DOKY-188 Refine conditions to run specific tests in build.gradle.kt

---

app-server/src/apiTest/kotlin/org/hkurh/doky/PasswordSpec.kt
app-server/src/apiTest/resources/sql/PasswordSpec/setup.sql
app-server/src/apiTest/resources/sql/cleanup_base_test_data.sql
app-server/src/integrationTest/kotlin/org/hkurh/doky/password/impl/DefaultPasswordFacadeIntegrationTest.kt
app-server/src/integrationTest/resources/sql/DefaultPasswordFacadeIntegrationTest/setup.sql
app-server/src/integrationTest/resources/sql/cleanup_base_test_data.sql
app-server/src/main/kotlin/org/hkurh/doky/errorhandling/DokyControllerAdvice.kt
app-server/src/main/kotlin/org/hkurh/doky/errorhandling/Exceptions.kt
app-server/src/main/kotlin/org/hkurh/doky/password/PasswordFacade.kt
app-server/src/main/kotlin/org/hkurh/doky/password/ResetPasswordService.kt
app-server/src/main/kotlin/org/hkurh/doky/password/api/PasswordApi.kt
app-server/src/main/kotlin/org/hkurh/doky/password/api/PasswordController.kt
app-server/src/main/kotlin/org/hkurh/doky/password/api/UpdatePasswordRequest.kt
app-server/src/main/kotlin/org/hkurh/doky/password/db/ResetPasswordTokenEntity.kt
app-server/src/main/kotlin/org/hkurh/doky/password/db/ResetPasswordTokenEntityRepository.kt
app-server/src/main/kotlin/org/hkurh/doky/password/impl/DefaultPasswordFacade.kt
app-server/src/main/kotlin/org/hkurh/doky/password/impl/DefaultResetPasswordService.kt
app-server/src/main/kotlin/org/hkurh/doky/security/JwtAuthorizationFilter.kt
app-server/src/main/kotlin/org/hkurh/doky/users/impl/DefaultUserFacade.kt
app-server/src/test/kotlin/org/hkurh/doky/password/DefaultPasswordFacadeTest.kt
app-server/src/test/kotlin/org/hkurh/doky/password/DefaultResetPasswordServiceTest.kt
email-service/src/integrationTest/resources/sql/cleanup_base_test_data.sql
email-service/src/main/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationConsumerService.kt
email-service/src/main/kotlin/org/hkurh/doky/password/db/ResetPasswordTokenEntityRepository.kt
email-service/src/test/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationConsumerServiceTest.kt

Add password update functionality
Refactor token repository naming and add password update API endpoints. Introduce handling for valid tokens in password update with corresponding tests and SQL setup.

DOKY-118 Create endpoint to Update password

---

app-server/doky-front/src/api/users.js
app-server/doky-front/src/components/formComponents/FormInput.jsx
app-server/doky-front/src/pages/UpdatePassword/UpdatePassword.jsx
app-server/doky-front/src/pages/UpdatePassword/index.js
app-server/doky-front/src/pages/UpdatePassword/useUpdatePassword.js
app-server/doky-front/src/routing/routes.js

Add `UpdatePassword` page
Implemented a new `UpdatePassword` page with associated hooks and API calls for user password updates. Also updated the routing configuration to include the new page and made minor adjustments to the `FormInput` component.

DOKY-189 Create page to update password

---

app-server/doky-front/src/components/Logo/Logo.jsx
app-server/doky-front/src/components/Logo/index.js
app-server/doky-front/src/pages/Login/Login.jsx
app-server/doky-front/src/pages/Register/Register.jsx
app-server/doky-front/src/pages/ResetPassword/ResetPassword.jsx
app-server/doky-front/src/pages/UpdatePassword/UpdatePassword.jsx

Refactor logo component usage across pages
Replace hardcoded logo references with the newly created reusable `Logo` component in multiple pages. This improves maintainability and consistency of the logo display throughout the application.

DOKY-194 Create component for Logo

---

app-server/build.gradle.kts
build.gradle.kts
email-service/build.gradle.kts
email-service/src/main/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationConsumerService.kt
email-service/src/main/resources/application.properties
email-service/src/main/resources/logback-spring.xml
teamcity/email-service.Dockerfile

Integrate versioning, logging, and deployment updates
Added unified versioning and build date across projects. Introduced JSON logging for production in `email-service` with `Logback`. Enhanced Docker configurations for both 'app-server' and 'email-service' with dynamic environment variables and deploy settings.

DOKY-204 Update deployment for `email-service`

---

ai-search/src/main/kotlin/org/hkurh/doky/AiSearchConfig.kt
ai-search/src/main/kotlin/org/hkurh/doky/search/LoggingPolicy.kt
indexer-service/src/main/kotlin/org/hkurh/doky/search/schedule/Scheduler.kt

Add documentation and reinstate logging policy
Added comprehensive documentation for the `Scheduler` interface to clarify its purpose and usage. Reincluded the `LoggingPolicy` in the AI search configuration and simplified logging implementation by excluding headers in debug logs for better readability.

DOKY-215 Fix sonar issues

---

indexer-service/build.gradle.kts
indexer-service/src/main/kotlin/org/hkurh/doky/IndexerServiceApplication.kt
indexer-service/src/main/kotlin/org/hkurh/doky/admin/SearchController.kt
indexer-service/src/main/kotlin/org/hkurh/doky/security/DokyUserDetails.kt
indexer-service/src/main/kotlin/org/hkurh/doky/security/JwtAuthorizationFilter.kt
indexer-service/src/main/kotlin/org/hkurh/doky/security/JwtProvider.kt
indexer-service/src/main/kotlin/org/hkurh/doky/security/SpringSecurityAuditorAware.kt
indexer-service/src/main/kotlin/org/hkurh/doky/security/WebSecurityConfig.kt

Add authentication and security layer to `indexer-service`
Introduced authentication with JWT and role-based access control. Added new security configurations, JWT utilities, and filters. Implemented admin feature for full indexing and updated dependencies to include necessary libraries.

DOKY-214 Add endpoint to start full indexing

---

README.md
doky-front/cypress.config.js
doky-front/cypress/e2e/login.cy.js
doky-front/cypress/support/commands.js
doky-front/cypress/support/e2e.js
doky-front/package-lock.json
doky-front/package.json

Add Cypress configuration and dependencies
Introduced a Cypress configuration file with the project ID and included Cypress along with related dependencies in `package-lock.json`. These changes aim to set up the testing environment for end-to-end testing using Cypress.

DOKY-239 Add E2E tests

---

src/main/kotlin/org/hkurh/doky/config/KafkaConsumerConfig.kt
src/main/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationProducerService.kt
src/test/kotlin/org/hkurh/doky/email/impl/SendgridEmailSenderTest.kt
src/test/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationProducerServiceTest.kt

This pull request incorporates error handling for Kafka consumers by using `DefaultErrorHandler` with Dead Letter Queue (DLQ) support. It also enhances Kafka message key traceability by appending a timestamp and email type. 
- **Added**: `ErrorHandlingDeserializer` for Kafka consumers for better error management.
- **Enhanced**: Kafka message keys with timestamp and email type to improve traceability.
- **Tests**: Improved assertions in `KafkaEmailNotificationProducerService` for robust test coverage.

DOKY-245 Implement `ErrorHandlingDeserializer` for kafka consumer

---

README.md
build.gradle.kts
src/main/resources/application.properties

- Adjusted `build.gradle.kts` deployVersion default to "0.1.0" for alignment.
- Updated logging levels in property files to enhance debugging capability.
- Improved formatting consistency and clarified existing configurations.
- Updated the TeamCity badge in `README.md` to reflect the status of UI E2E tests.

DOKY-246 Update project configurations and adjust build versioning

---

doky-front/package-lock.json
doky-front/package.json
doky-front/src/pages/Login/Login.jsx
doky-front/src/pages/ResetPassword/ResetPassword.jsx
doky-front/src/pages/UpdatePassword/UpdatePassword.jsx
doky-front/src/routing/routes.js

- **Refactor password-related forms using Material-UI:**  
Updated `ResetPassword`, `Login`, and `UpdatePassword` components to align with Material-UI guidelines, replacing Bootstrap styling for consistency and maintainability. Improved layouts using `Stack` and enhanced accessibility. Adjusted the `reset-password` route to `password/reset` for better structure.

DOKY-248 Refactor password-related forms using Material-UI components
