- server/src/main/java/org/hkurh/doky/security/JwtAuthorizationFilter.kt
When request is for endpoints that should be accessed only by anonymous user, token is not checked at all.
It is needed when user's browser contains a expired token and it tries to login or register.
> MAIN-T-95 Do not access token for anonymous requests

- .gitignore
- server/src/apiTest/java/org/hkurh/doky/PasswordSpec.kt
- server/src/apiTest/java/org/hkurh/doky/RestSpec.kt
- server/src/apiTest/resources/sql/DocumentSpec/setup.sql
- server/src/apiTest/resources/sql/SearchSpec/setup.sql
- server/src/apiTest/resources/sql/cleanup_base_test_data.sql
- server/src/apiTest/resources/sql/create_base_test_data.sql
- server/src/main/java/org/hkurh/doky/email/EmailService.kt
- server/src/main/java/org/hkurh/doky/password/PasswordFacade.kt
- server/src/main/java/org/hkurh/doky/password/ResetPasswordService.kt
- server/src/main/java/org/hkurh/doky/password/TokenUtil.kt
- server/src/main/java/org/hkurh/doky/password/api/PasswordApi.kt
- server/src/main/java/org/hkurh/doky/password/api/PasswordController.kt
- server/src/main/java/org/hkurh/doky/password/api/ResetPasswordRequest.kt
- server/src/main/java/org/hkurh/doky/password/db/ResetPasswordTokenEntity.kt
- server/src/main/java/org/hkurh/doky/password/db/ResetPasswordTokenRepository.kt
- server/src/main/java/org/hkurh/doky/security/JwtAuthorizationFilter.kt
- server/src/main/java/org/hkurh/doky/users/UserFacade.kt
- server/src/main/java/org/hkurh/doky/users/UserService.kt
- server/src/main/java/org/hkurh/doky/users/db/UserEntityRepository.kt
- server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-test.properties
- server/src/main/resources/application.properties
- server/src/main/resources/db/migration/V14__create_reset_password_token.sql
- server/src/main/resources/mail/templates/restore-password.html
- server/src/test/java/org/hkurh/doky/password/PasswordFacadeTest.kt
- server/src/test/java/org/hkurh/doky/password/ResetPasswordServiceTest.kt
- server/src/test/java/org/hkurh/doky/users/UserFacadeTest.kt
Add password reset feature with token generation and email notification
- Implemented a password reset functionality that checks user existence, generates a reset password token, and sends an email notification with the reset password token.
- Created relevant test cases and updated user service and user facade.
- Added endpoint to reset password and updated JwtAuthorizationFilter for password reset endpoint.
- Included new database table for storing reset password tokens.
> MAIN-T-117 Create endpoint to send Restore Password email

- server/src/apiTest/kotlin/org/hkurh/doky/DocumentSpec.kt
- server/src/apiTest/kotlin/org/hkurh/doky/LoginSpec.kt
- server/src/apiTest/kotlin/org/hkurh/doky/PasswordSpec.kt
- server/src/apiTest/kotlin/org/hkurh/doky/RegistrationSpec.kt
- server/src/apiTest/kotlin/org/hkurh/doky/RestSpec.kt
- server/src/main/kotlin/org/hkurh/doky/DokyController.kt
- server/src/main/kotlin/org/hkurh/doky/authorization/AuthorizationUserController.kt
- server/src/main/kotlin/org/hkurh/doky/documents/api/DocumentController.kt
- server/src/main/kotlin/org/hkurh/doky/password/api/PasswordController.kt
- server/src/main/kotlin/org/hkurh/doky/security/JwtAuthorizationFilter.kt
- server/src/main/kotlin/org/hkurh/doky/users/api/UserController.kt
- server/src/main/resources/application.properties
Refactor API routes to use `/api` prefix
API endpoints across the application have been refactored to include an `/api` prefix. Tests have been updated to reflect this change. This makes the application follow standard RESTful API conventions better and makes differentiating between frontend and backend requests clearer.
> DOKY-153 Add prefix for API

- server/src/apiTest/kotlin/org/hkurh/doky/PasswordSpec.kt
- server/src/apiTest/kotlin/org/hkurh/doky/UserSpec.kt
- server/src/main/kotlin/org/hkurh/doky/users/UserFacade.kt
- server/src/main/kotlin/org/hkurh/doky/users/api/UpdateUserRequest.kt
- server/src/main/kotlin/org/hkurh/doky/users/api/UserApi.kt
- server/src/main/kotlin/org/hkurh/doky/users/api/UserController.kt
- server/src/main/kotlin/org/hkurh/doky/users/impl/DefaultUserFacade.kt
Replace `UserDto` with `UpdateUserRequest` in update user flow
Standardize the update user request handling by changing from `UserDto` to UpdateUserRequest in order do not validate password as it should not be sent. Adjusted endpoints, validation classes, and the facade to ensure proper handling of user update logic. Also added new `UserSpec` tests to validate the functionality.
> DOKY-169 Could not to update username

- server/src/apiTest/kotlin/org/hkurh/doky/PasswordSpec.kt
- server/src/main/kotlin/org/hkurh/doky/password/api/PasswordApi.kt
- server/src/main/kotlin/org/hkurh/doky/password/impl/DefaultPasswordFacade.kt
- server/src/test/kotlin/org/hkurh/doky/password/DefaultPasswordFacadeTest.kt
Refactor password reset to handle non-existent users gracefully and avoiding the exception. The reason is to not expose information about emails that are used by registered users.
> DOKY-170 Error-free response for password restoration with non-existent email

- server/src/apiTest/kotlin/org/hkurh/doky/PasswordSpec.kt
- server/src/apiTest/resources/sql/cleanup_base_test_data.sql
- server/src/main/kotlin/org/hkurh/doky/password/db/ResetPasswordTokenEntity.kt
- server/src/main/kotlin/org/hkurh/doky/password/impl/DefaultPasswordFacade.kt
- server/src/main/resources/db/migration/sqlserver/V1_4__rename_user_column_in_reset_password.sql
Rename `user` column to `app_user` in reset password tables
Updated the `reset_password_tokens` table to rename the `user` column to `app_user` to address SQL Server reserved keyword issues. Adjusted entity classes, test specifications, and SQL scripts accordingly.
> DOKY-173 Fix disabled Password API test

- server/build.gradle.kts
- server/src/apiTest/kotlin/org/hkurh/doky/EmbeddedKafkaConsumerConfig.kt
- server/src/apiTest/kotlin/org/hkurh/doky/RestSpec.kt
- server/src/integrationTest/kotlin/org/hkurh/doky/DokyIntegrationTest.kt
- server/src/integrationTest/kotlin/org/hkurh/doky/EmbeddedKafkaConsumerConfig.kt
- server/src/integrationTest/kotlin/org/hkurh/doky/users/DefaultUserServiceIntegrationTest.kt
- server/src/main/kotlin/org/hkurh/doky/KafkaProducerConfig.kt
- server/src/main/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationService.kt
- server/src/main/kotlin/org/hkurh/doky/kafka/SendEmailMessage.kt
- server/src/main/kotlin/org/hkurh/doky/password/impl/DefaultPasswordFacade.kt
- server/src/main/kotlin/org/hkurh/doky/users/impl/DefaultUserService.kt
- server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-test.properties
- server/src/main/resources/application.properties
- server/src/test/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationServiceTest.kt
- server/src/test/kotlin/org/hkurh/doky/password/DefaultPasswordFacadeTest.kt
- server/src/test/kotlin/org/hkurh/doky/users/DefaultUserServiceTest.kt
Add Kafka integration for email notifications
Added Kafka producer configurations for email notifications. Implemented Kafka email notification service and integrated it in user registration and password reset flows. Updated tests to incorporate Kafka messages.
> DOKY-178 Add message to Kafka to send email

- email-service/build.gradle.kts
- email-service/src/main/resources/application.properties
Add Spring Boot Web Starter and enable Actuator endpoints
Refactor `build.gradle.kts` to include Spring Boot Web Starter and improve dependency management by using version variables. Enable Actuator endpoints by default in `application.properties` to support monitoring needs.
> DOKY-172 Create separate email service

- email-service/build.gradle.kts
- email-service/src/integrationTest/kotlin/org/hkurh/doky/kafka/KafkaEmailNotificationConsumerServiceIntegrationTest.kt
- email-service/src/integrationTest/resources/sql/KafkaEmailNotificationConsumerServiceIntegrationTest/setup.sql
- email-service/src/integrationTest/resources/sql/cleanup_base_test_data.sql
- email-service/src/integrationTest/resources/sql/create_base_test_data.sql
- email-service/src/main/kotlin/org/hkurh/doky/email/EmailProperties.kt
- email-service/src/main/kotlin/org/hkurh/doky/email/impl/DefaultEmailService.kt
- email-service/src/main/kotlin/org/hkurh/doky/email/impl/SendgridEmailService.kt
- email-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- email-service/src/main/resources/application-test.properties
- email-service/src/main/resources/application.properties
- email-service/src/test/kotlin/org/hkurh/doky/email/impl/DefaultEmailServiceTest.kt
- email-service/src/test/kotlin/org/hkurh/doky/email/impl/SendgridEmailServiceTest.kt
Introduce SendGrid email service and update properties
Added support for sending emails via SendGrid, including the necessary configurations and properties. Refactored `DefaultEmailService` to use `EmailProperties` for more flexible email settings.
> DOKY-186 Send emails using SendGrid REST API

- app-server/doky-front/src/pages/NotFoundPage.jsx
Remove redundant header from `NotFoundPage`
Refactored the `NotFoundPage` component to eliminate the redundant navbar header. This change simplifies the component structure and enhances layout consistency.
> DOKY-187 Remove the header on the 404 page

- app-server/build.gradle.kts
- app-server/src/main/kotlin/org/hkurh/doky/documents/api/DocumentController.kt
- gradle/libs.versions.toml
- teamcity/app-server.Dockerfile
Add Datadog tracing and configuration
Introduce Datadog tracing for key API operations in `DocumentController` using `@Trace` annotations. Update Gradle dependencies and Dockerfile to enable Datadog features such as logs, profiling, and APM. Adjusted Docker entrypoint and commands to initialize Datadog.
> DOKY-203 Configure Datadog Database monitoring

- app-server/build.gradle.kts
- build.gradle.kts
- email-service/build.gradle.kts
- email-service/src/main/kotlin/org/hkurh/doky/EmailServiceApplication.kt
- email-service/src/main/resources/application.properties
- email-service/src/main/resources/logback-spring.xml
- teamcity/email-service.Dockerfile
Set up non-web `email-service` and enhance observability
Configured `email-service` to run as a non-web application by disabling the web application type. Added a dedicated `Dockerfile` for `email-service` with Datadog integration and introduced a production-specific JSON logging configuration. Adjusted environment configurations to improve flexibility and maintain consistency across services.
> DOKY-204 Update deployment for email-service

- app-server/src/apiTest/kotlin/org/hkurh/doky/DocumentSpec.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/DocumentFacade.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/DocumentService.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/DownloadTokenService.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/api/DocumentApi.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/api/DocumentController.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/api/DownloadFileRequest.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/impl/DefaultDocumentFacade.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/impl/DefaultDocumentService.kt
- app-server/src/main/kotlin/org/hkurh/doky/documents/impl/DefaultDownloadTokenService.kt
- app-server/src/main/kotlin/org/hkurh/doky/errorhandling/DokyControllerAdvice.kt
- app-server/src/main/kotlin/org/hkurh/doky/filestorage/impl/DokyAzureBlobStorage.kt
- app-server/src/main/kotlin/org/hkurh/doky/security/JwtProvider.kt
- app-server/src/test/kotlin/org/hkurh/doky/documents/impl/DefaultDocumentFacadeTest.kt
Refactor download token handling and enhance validation
Moved download token logic from `DocumentService` to a new `DownloadTokenService` to improve separation of concerns. Updated APIs to consistently use Long for IDs and introduced a more robust download token validation mechanism. Adjusted related tests and documentation for improved clarity and accuracy.
> DOKY-208 Update file download endpoint to use temporary download token

- email-service/src/main/kotlin/org/hkurh/doky/email/impl/SendgridEmailService.kt
- email-service/src/test/kotlin/org/hkurh/doky/email/impl/SendgridEmailServiceTest.kt
Add handling for SendGrid API errors in email service
Enhanced error handling in `SendgridEmailService` to log errors for non-2xx responses from the SendGrid API.
> DOKY-206 Adjust error handling from SendGrid

- app-server/build.gradle.kts
Update `Node.js` version to `22.13.1` in `Gradle` build file
Upgraded `Node.js` from `20.12.2` to `22.13.1` in the build configuration. This ensures compatibility with the latest dependencies and introduces performance and security improvements. No other changes were made to the configuration.
> DOKY-211 Switch CI/CD to node 22

- app-server/doky-front/src/api/documents.js
- app-server/doky-front/src/api/request.js
- app-server/doky-front/src/pages/Documents/EditDocumentForm/EditDocumentForm.jsx
- app-server/doky-front/src/services/save-file.js
To meet the following requirements:
File download should be performed via POST request
Download request should contain a JSON body
Large files (current limit is 10 MB) can be downloaded
I decided to use the experimental browser API. The introduced approach allows receiving a readable stream and redirecting it to the file system.
https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeTo
A disadvantage here is the poor integration with the browser UI: https://github.com/WICG/file-system-access/issues/379
1. Fetch file content completely, convert it to base 64, insert it into a hidden link, and emulate a click. This is not appropriate due to excess memory usage.
2. Create a hidden form and emulate a …
> DOKY-145 download file

- indexer-service/src/integrationTest/kotlin/org/hkurh/doky/search/index/impl/DefaultIndexServiceIntegrationTest.kt
- persistence/src/main/resources/migration/mysql/V1_6__add_admin_user.sql
- persistence/src/main/resources/migration/sqlserver/V1_6__add_admin_user.sql
Add SQL scripts to insert default admin user
This commit introduces migration scripts for both SQL Server and MySQL to ensure a default admin user is created if it doesn't already exist. The user is assigned the `ROLE_ADMIN` authority to enable administrative privileges.
> DOKY-115 Add administrator user

- app-server/src/main/resources/logback-spring.xml
- email-service/src/main/resources/logback-spring.xml
- indexer-service/src/main/resources/logback-spring.xml
- teamcity/app-server.Dockerfile
- teamcity/email-service.Dockerfile
- teamcity/indexer-service.Dockerfile
Update logging configurations and simplify Dockerfiles
Revised logback configurations to use a streamlined encoder and adjusted profile names for consistency. Simplified Dockerfiles by removing the spring profile argument from CMD and adding port exposure for services where appropriate. These changes standardize configuration and improve maintainability across services.
> DOKY-216 Adjust logging and spring profile configurations for the production Docker environment

- app-server/build.gradle.kts
- app-server/src/main/resources/application.properties
- email-service/build.gradle.kts
- email-service/src/main/resources/application.properties
- gradle/libs.versions.toml
- indexer-service/build.gradle.kts
- indexer-service/src/main/resources/application.properties
Add Spring Boot Admin support across services
Integrated Spring Boot Admin dependencies and configurations into email-service, app-server, and indexer-service. Updated `application.properties` files to include required settings for Actuator and Spring Boot Admin client. Adjusted `libs.versions.toml` to define the Spring Boot Admin version.
> DOKY-199 Add Spring Boot Admin client to app-server

- app-server/src/main/resources/application.properties
- email-service/src/main/resources/application.properties
- indexer-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- indexer-service/src/main/resources/application.properties
Remove Spring Boot Admin client configuration
Spring Boot Admin client configuration was commented out and is no longer needed. This cleanup ensures the application properties files remain concise and free of unused configurations. It has no impact on the existing functionality.
> DOKY-232 Remove Spring Admin

- .github/workflows/publish-javadoc.yml
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
Upgrade Dokka to 2.0.0.
Updated Dokka to the latest major version 2.0.0 for improved functionality. Added forced version resolution for Jackson dependencies and introduced a new `gradle.properties` file for Gradle configurations.
Additionally, removed obsolete Azure and Spring-related dependencies and bundles to streamline the build configuration.
> DOKY-185 Update the workflow to publish Javadocs
